/* reveal */
(function(){const els=document.querySelectorAll('.rv');if(!('IntersectionObserver' in window)){els.forEach(e=>e.classList.add('in'));return;}const io=new IntersectionObserver(entries=>{entries.forEach(en=>{if(en.isIntersecting){en.target.classList.add('in');io.unobserve(en.target);}})},{threshold:.12,rootMargin:'0px 0px -40px 0px'});els.forEach(e=>io.observe(e));})();
/* counters */
(function(){if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.count').forEach(c=>c.textContent=(+c.dataset.target).toLocaleString());return;}const io=new IntersectionObserver(entries=>{entries.forEach(en=>{if(!en.isIntersecting)return;io.unobserve(en.target);const el=en.target,target=+el.dataset.target,dur=1400,t0=performance.now();(function tick(t){const p=Math.min((t-t0)/dur,1),ease=1-Math.pow(1-p,3);el.textContent=Math.round(target*ease).toLocaleString();if(p<1)requestAnimationFrame(tick);})(t0);});},{threshold:.6});document.querySelectorAll('.count').forEach(c=>io.observe(c));})();
/* steam */
(function(){if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const field=document.getElementById('steamField');if(!field)return;for(let i=0;i<16;i++){const s=document.createElement('div');s.className='steam';const size=50+Math.random()*130;s.style.width=size+'px';s.style.height=size+'px';s.style.left=Math.random()*100+'%';s.style.animationDuration=(9+Math.random()*11)+'s';s.style.animationDelay=(Math.random()*-20)+'s';field.appendChild(s);}})();
/* ticker */
(function(){const t=document.getElementById('tickerTrack');if(t)t.innerHTML+=t.innerHTML;})();
/* before after */
(function(){const frame=document.getElementById('baFrame');if(!frame)return;const setCut=p=>{p=Math.max(2,Math.min(98,p));frame.style.setProperty('--cut',p+'%');frame.setAttribute('aria-valuenow',Math.round(p));};const fromEvent=e=>{const r=frame.getBoundingClientRect();const x=e.clientX-r.left;setCut(x/r.width*100);};let dragging=false;frame.addEventListener('pointerdown',e=>{dragging=true;frame.setPointerCapture(e.pointerId);fromEvent(e);});frame.addEventListener('pointermove',e=>{if(dragging)fromEvent(e);});frame.addEventListener('pointerup',()=>dragging=false);frame.addEventListener('pointercancel',()=>dragging=false);frame.addEventListener('keydown',e=>{const cur=parseFloat(getComputedStyle(frame).getPropertyValue('--cut'))||50;if(e.key==='ArrowLeft'){setCut(cur-4);e.preventDefault();}if(e.key==='ArrowRight'){setCut(cur+4);e.preventDefault();}});})();
/* reviews */
const REVIEWS=[{name:'Tracy X.',date:'Verified client',text:'They do a very good job for us. Very dependable. During COVID, we had to deep clean and they were able to come the same day we needed it done.',source:'HomeAdvisor'}];
(function renderReviews(){const strip=document.getElementById('revStrip');if(!strip)return;REVIEWS.forEach(r=>{const card=document.createElement('article');card.className='rev-card';const stars='★'.repeat(r.stars||5);card.innerHTML='<div class="stars" aria-label="'+(r.stars||5)+' out of 5 stars">'+stars+'</div><blockquote></blockquote><div class="rev-meta"><span class="avatar">'+r.name.charAt(0).toUpperCase()+'</span><span><b></b><small></small></span><span class="rev-src">'+r.source+'</span></div>';card.querySelector('blockquote').textContent='"'+r.text+'"';card.querySelector('b').textContent=r.name;card.querySelector('small').textContent=r.date;strip.appendChild(card);});const cta=document.createElement('article');cta.className='rev-card cta-card';cta.innerHTML='<div><h3>Worked with us before?</h3><p>A review helps your neighbors find a cleaner they can trust.</p><a class="btn btn-primary" href="#quote">Get a free estimate ★</a></div>';strip.appendChild(cta);})();
function scrollRevs(dir){const strip=document.getElementById('revStrip');if(strip)strip.scrollBy({left:dir*400,behavior:'smooth'});}
/* tabs */
function switchTab(which){const res=which==='res';document.getElementById('gridRes').style.display=res?'grid':'none';document.getElementById('gridCom').style.display=res?'none':'grid';document.getElementById('tabRes').classList.toggle('active',res);document.getElementById('tabCom').classList.toggle('active',!res);document.getElementById('tabRes').setAttribute('aria-selected',res);document.getElementById('tabCom').setAttribute('aria-selected',!res);const grid=document.getElementById(res?'gridRes':'gridCom');grid.querySelectorAll('.rv').forEach(e=>e.classList.add('in'));}
/* quote form */
function sendQuote(){const n=document.getElementById('f-name').value.trim();const p=document.getElementById('f-phone').value.trim();const s=document.getElementById('f-service').value;const m=document.getElementById('f-msg').value.trim();if(!n||!p){alert('Please add your name and phone number so we can reach you.');return;}const body=encodeURIComponent('Name: '+n+'\nPhone: '+p+'\nService: '+s+'\n\nDetails:\n'+m);window.location.href='mailto:quotes@cascadecleaningpdx.com?subject='+encodeURIComponent('Free Estimate Request — '+s)+'&body='+body;}
/* static assistant */
let chatBusy=false;function toggleChat(){const p=document.getElementById('chatPanel');p.classList.toggle('open');const b=document.getElementById('chatBadge');if(b)b.style.display='none';if(p.classList.contains('open'))document.getElementById('chatInput').focus();}function quickAsk(q){document.getElementById('chatInput').value=q;sendChat();}function addMsg(text,who){const b=document.getElementById('chatBody');const d=document.createElement('div');d.className='msg '+who;d.textContent=text;b.appendChild(d);b.scrollTop=b.scrollHeight;return d;}function botReply(text){const q=text.toLowerCase();const lead=' For a free estimate, send your name and phone or call (971) 344-1026.';if(q.includes('price')||q.includes('cost')||q.includes('how much'))return 'Pricing depends on the job size, stains, odor, access, and service. Estimates are free.'+lead;if(q.includes('pet')||q.includes('odor')||q.includes('urine'))return 'Yes. Cascade uses enzyme treatment plus hot water extraction at the pad level to break down urine crystals, not just mask smell.'+lead;if(q.includes('office')||q.includes('janitorial')||q.includes('commercial')||q.includes('warehouse'))return 'Yes. Cascade handles recurring janitorial, commercial deep cleans, warehouse floor care, storefronts, and post-construction cleanup.'+lead;if(q.includes('dry'))return 'With the Dry-Master system, carpets can dry in as little as 4 hours depending on airflow, humidity, and carpet condition.'+lead;return 'Cascade helps with carpet, tile and grout, upholstery, area rugs, pet odor, windows, pressure washing, janitorial, and post-construction cleaning.'+lead;}async function sendChat(){if(chatBusy)return;const input=document.getElementById('chatInput');const text=input.value.trim();if(!text)return;input.value='';const quick=document.getElementById('chatQuick');if(quick)quick.style.display='none';addMsg(text,'user');chatBusy=true;document.getElementById('chatSend').disabled=true;const typing=document.createElement('div');typing.className='msg bot typing';typing.innerHTML='<span></span><span></span><span></span>';document.getElementById('chatBody').appendChild(typing);document.getElementById('chatBody').scrollTop=1e9;setTimeout(()=>{typing.remove();addMsg(botReply(text),'bot');chatBusy=false;document.getElementById('chatSend').disabled=false;},450);}
