const businessPhone='(971) 344-1026';
function initReveal(){const items=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('show'));return}const obs=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('show');obs.unobserve(entry.target)}})},{threshold:.12});items.forEach(i=>obs.observe(i))}
function setupLeadForm(){const form=document.getElementById('leadForm');const status=document.getElementById('formStatus');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('button[type="submit"]');const original=btn.textContent;btn.disabled=true;btn.textContent='Sending...';status.textContent='';try{const res=await fetch(form.action,{method:'POST',headers:{Accept:'application/json'},body:new FormData(form)});if(!res.ok)throw new Error('not sent');form.reset();status.textContent='Sent. The team will call you back soon.';btn.textContent='Request sent ✓';setTimeout(()=>{btn.disabled=false;btn.textContent=original},2500)}catch(err){status.textContent='Could not send. Call '+businessPhone+' instead.';btn.disabled=false;btn.textContent=original}})}
function toggleChat(){const p=document.getElementById('chatPanel');if(p)p.classList.toggle('open')}
function addMsg(text,who){const log=document.getElementById('chatLog');if(!log)return;const d=document.createElement('div');d.className='msg '+who;d.textContent=text;log.appendChild(d);log.scrollTop=log.scrollHeight}
function answerQuestion(text){const q=text.toLowerCase();const quote='For a free estimate, call '+businessPhone+' or send the quote form.';if(q.includes('price')||q.includes('cost')||q.includes('how much'))return 'Pricing depends on square footage, stains, odor, access, and service type. '+quote;if(q.includes('pet')||q.includes('odor')||q.includes('urine'))return 'Yes. Cascade handles pet stain and odor jobs with enzyme treatment and hot-water extraction. '+quote;if(q.includes('office')||q.includes('commercial')||q.includes('janitorial')||q.includes('warehouse'))return 'Yes. Cascade cleans offices, storefronts, warehouses, rentals, and post-construction jobs. '+quote;if(q.includes('dry'))return 'Carpets can dry in as little as 4 hours depending on airflow, carpet condition, and humidity.';return 'Cascade cleans carpets, tile and grout, upholstery, pet odor, windows, pressure washing, commercial janitorial, and post-construction jobs. '+quote}
function quickAsk(text){const input=document.getElementById('chatInput');if(input)input.value=text;sendChat()}
function sendChat(){const input=document.getElementById('chatInput');if(!input)return;const text=input.value.trim();if(!text)return;input.value='';addMsg(text,'user');setTimeout(()=>addMsg(answerQuestion(text),'bot'),220)}
document.addEventListener('DOMContentLoaded',()=>{initReveal();setupLeadForm()});
